### ISSUE TITLE
image upload does not works

### ISSUE THREAD

**Issue by Mirodil** [jeremyfa/docpad-plugin-minicms#24]
image upload does not works at all because `req.files` is empty(undefined) in the `router\upload.js` and returns 404 from the [#L112](https://github.com/jeremyfa/docpad-plugin-minicms/blob/master/out/routes/upload.js#L112).
In order to fix this, needs to change the following line [#L74](https://github.com/jeremyfa/docpad-plugin-minicms/blob/master/out/minicms.plugin.js#L74)
```
return app.post('/' + this.config.prefix.url + '/:content/:field/upload', cp, cs, express.bodyParser({ keepExtensions: true }), require('./routes/upload').bind(this));
```

**Comment by jeremyfa** [comment]
Thanks for reporting, I will test with this change and see if it solves the issue.
