### ISSUE TITLE
image field is not working

### ISSUE THREAD

**Issue by dospuntocero** [jeremyfa/docpad-plugin-minicms#7]
im getting this error:

error: An error occured: 
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)

**Comment by derberg** [comment]
I'm having exactly the same problem even when running the example from this repo
`POST http://localhost:9778/cms/article/image/upload 404 (Not Found)`
@dospuntocero did you find a solution for it?
